services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    # Register EventListener 
    bugbuster.dlstats.kernelresponse_listener:
        class: "BugBuster\\DlstatsBundle\\EventListener\\DownloadResponseListener"
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response}

    bugbuster.dlstats.insert_tags_listener:
        class: "BugBuster\\DlstatsBundle\\EventListener\\ReplaceInsertTagsListener"
        public: true
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
