services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    # Register EventListener 
    bugbuster.dlstats.kernelresponse_listener:
        class: "BugBuster\\DlstatsBundle\\EventListener\\DownloadResponseListener"
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response}
